version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.APPLICATION

- url: /checkmodel
  script: main.APPLICATION
  login: admin

- url: /trainmodel
  script: main.APPLICATION
  login: admin